// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyArq-LJqJAJMb_QkLYsRhpBNz_9UVktg',
    appId: '1:566331666414:web:760e6bad349edf58a068ff',
    messagingSenderId: '566331666414',
    projectId: 'job-timer-rtyota',
    authDomain: 'job-timer-rtyota.firebaseapp.com',
    storageBucket: 'job-timer-rtyota.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXjGIrqKx2ziNkik8-4pY-kHI9UIQrpeY',
    appId: '1:566331666414:android:9ff35e6a9a84872aa068ff',
    messagingSenderId: '566331666414',
    projectId: 'job-timer-rtyota',
    storageBucket: 'job-timer-rtyota.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZeYM_k5e7UOXtm3oRgkX552wooJMtoEQ',
    appId: '1:566331666414:ios:52e9bf1f1e66e91fa068ff',
    messagingSenderId: '566331666414',
    projectId: 'job-timer-rtyota',
    storageBucket: 'job-timer-rtyota.appspot.com',
    iosClientId: '566331666414-njkpc6lifunqrehvtmm51g3je0j18bo9.apps.googleusercontent.com',
    iosBundleId: 'br.com.rtyota.jobTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZeYM_k5e7UOXtm3oRgkX552wooJMtoEQ',
    appId: '1:566331666414:ios:52e9bf1f1e66e91fa068ff',
    messagingSenderId: '566331666414',
    projectId: 'job-timer-rtyota',
    storageBucket: 'job-timer-rtyota.appspot.com',
    iosClientId: '566331666414-njkpc6lifunqrehvtmm51g3je0j18bo9.apps.googleusercontent.com',
    iosBundleId: 'br.com.rtyota.jobTimer',
  );
}
